# Generated by Django 2.2 on 2019-04-26 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_title', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('animation', models.URLField()),
                ('sfx', models.URLField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BooksAdmin.Book')),
                ('parent_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BooksAdmin.Chapter')),
            ],
        ),
    ]
