# Generated by Django 2.2 on 2019-04-27 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BooksAdmin', '0002_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='animation',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='parent_chapter',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BooksAdmin.Chapter'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='sfx',
            field=models.URLField(blank=True),
        ),
    ]
