# Generated by Django 2.2 on 2019-04-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksAdmin', '0004_auto_20190427_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='ch_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
