# Generated by Django 2.2 on 2019-05-10 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BooksAdmin', '0005_chapter_ch_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Save',
        ),
    ]
