# Generated by Django 2.2 on 2019-05-14 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_save_current_chapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='save',
            old_name='player',
            new_name='user',
        ),
    ]
