# Generated by Django 2.2 on 2019-05-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0003_auto_20190514_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='save',
            old_name='user',
            new_name='player',
        ),
    ]
