# Generated by Django 2.2 on 2019-05-17 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0004_auto_20190514_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save',
            name='current_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BooksAdmin.Chapter'),
        ),
    ]
